export default{
    name:'spot',
    title:'Spot',
    type:'document',
    fields:[
        {
            name:'title',
            title:'Title',
            type:'string'
        },
        {
            name:'about',
            title:'About',
            type:'string'
        },
        {
            name:'url',
            title:'Url',
            type:'url'
        },
        {
            name:'category',
            title:'Category',
            type:'string'
        },
        {
            name:'image',
            title:'Image',
            type:'image',
            options:{
                hotspot:true
            }
        },
        {
            name:'userId',
            title:'UserId',
            type:'string'
        },
        {
            name:'postedBy',
            title:'PostedBy',
            type:'postedBy',
        },
        {
            name:'save',
            title:'Save',
            type:'array',
            of :[{type:'save'}]
        },
        {
            name:'comments',
            title:'Comments',
            type:'array',
            of:[{type:'comments'}]
        },
        {
            name:'reactions',
            title:'Reactions',
            type:'array',
            of:[{type:'reactions'}]
        }
    ]
}